### ISSUE TITLE
Final_files folder is not available  

### ISSUE THREAD

**Issue by CodeTerminator007** [ArpanSM/Product-s-Name-and-Price-Recognition-on-Store-Shelf#1]
Final Files folder is not available on google drive link its broken can you reupload the files or send the new link

**Comment by BiswarupMukherjee1** [comment]
I am facing the same problem. Please give the correct drive link. It will be really helpful.

**Comment by CodeTerminator007** [comment]
> 

I Didn't receive the Final Files From him.
